CREATE TABLE users (
    `ID` INT (10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `USERNAME` VARCHAR (32) NOT NULL,
    `EMAIL` VARCHAR (32) NOT NULL,
    `PASSWORD` TEXT NOT NULL,
    `HASH` VARCHAR (32) NOT NULL,
    `ACTIVE` VARCHAR (32) NOT NULL DEFAULT '0'
);